# Generated by Django 4.0.1 on 2022-02-21 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_vacancies_delete_job_delete_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
