# Generated by Django 4.0.1 on 2022-02-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_vacancies_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
