# Generated by Django 4.0.1 on 2022-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_vacancies_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
