# Generated by Django 4.0.1 on 2022-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_applicant_vacancies_applicants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='country',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
