# Generated by Django 4.0.1 on 2022-03-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_location_vacancies_city_vacancies_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='salary',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
