# Generated by Django 4.0.1 on 2022-03-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_vacancies_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='requirements',
            field=models.TextField(default=2000),
            preserve_default=False,
        ),
    ]
